package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF005FB0)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD3E4FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D36)
val md_theme_light_secondary = Color(0xFF44474E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE1E2EC)
val md_theme_light_onSecondaryContainer = Color(0xFF1B1B1F)
val md_theme_light_background = Color(0xFFF3F4F9)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFFFFFFF)
val md_theme_light_onSurfaceVariant = Color(0xFF44474E)
val md_theme_light_outline = Color(0xFFBAC7DB)
val md_theme_light_outlineVariant = Color(0xFFE1E2EC)

val md_theme_dark_primary = Color(0xFF005FB0) // Force light aesthetics for now or adjust dark later
val md_theme_dark_onPrimary = Color(0xFFFFFFFF)
val md_theme_dark_primaryContainer = Color(0xFFD3E4FF)
val md_theme_dark_onPrimaryContainer = Color(0xFF001D36)
val md_theme_dark_secondary = Color(0xFF44474E)
val md_theme_dark_onSecondary = Color(0xFFFFFFFF)
val md_theme_dark_secondaryContainer = Color(0xFFE1E2EC)
val md_theme_dark_onSecondaryContainer = Color(0xFF1B1B1F)
val md_theme_dark_background = Color(0xFFF3F4F9)
val md_theme_dark_onBackground = Color(0xFF1B1B1F)
val md_theme_dark_surface = Color(0xFFFFFFFF)
val md_theme_dark_onSurface = Color(0xFF1B1B1F)
val md_theme_dark_surfaceVariant = Color(0xFFFFFFFF)
val md_theme_dark_onSurfaceVariant = Color(0xFF44474E)
val md_theme_dark_outline = Color(0xFFBAC7DB)
val md_theme_dark_outlineVariant = Color(0xFFE1E2EC)
